// API响应类型定义
export const RESPONSE_CODES = {
  SUCCESS: 10000,
  AUTH_FAILED: 1001,
  PERMISSION_DENIED: 1002,
  VALIDATION_FAILED: 1003,
  NOT_FOUND: 1004,
  BUSINESS_CONFLICT: 1005,
  RATE_LIMITED: 1006,
  SERVER_ERROR: 1007
}

export const HTTP_STATUS = {
  OK: 200,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  TOO_MANY_REQUESTS: 429,
  INTERNAL_SERVER_ERROR: 500
}

// 错误消息映射
export const ERROR_MESSAGES = {
  [RESPONSE_CODES.AUTH_FAILED]: '认证失败，请重新登录',
  [RESPONSE_CODES.PERMISSION_DENIED]: '权限不足',
  [RESPONSE_CODES.VALIDATION_FAILED]: '参数验证失败',
  [RESPONSE_CODES.NOT_FOUND]: '资源不存在',
  [RESPONSE_CODES.BUSINESS_CONFLICT]: '业务冲突',
  [RESPONSE_CODES.RATE_LIMITED]: '请求过于频繁，请稍后再试',
  [RESPONSE_CODES.SERVER_ERROR]: '服务器错误，请稍后再试'
}
